In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
a.size

3

In [7]:
a.dtype

dtype('int32')

In [8]:
a[0]

1

In [9]:
a[-1]

3

In [10]:
a[0:2]

array([1, 2])

In [16]:
a2 = np.zeros( (3,3), dtype=np.int32)

In [17]:
a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
a2.dtype, a2.size

(dtype('float64'), 9)

In [20]:
a3 = np.arange(1,11,2)

In [21]:
a3

array([1, 3, 5, 7, 9])

In [23]:
a4 = np.random.randint(1,100,10)

In [24]:
a4

array([47, 21, 48, 19, 12, 80, 75, 17, 62, 56])

In [29]:
a4 = np.random.rand(10)

In [30]:
a4

array([0.99499304, 0.16803725, 0.78851834, 0.21465563, 0.36978202,
       0.87862776, 0.75095272, 0.08325572, 0.0715717 , 0.26445583])

### linspace

In [40]:
a,s = np.linspace(1,100,10,retstep=True)

In [41]:
a

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [42]:
s

11.0

In [43]:
type(a)

numpy.ndarray

### Fancy Indexing 

In [47]:
a = np.random.randint(1,100,10)

In [48]:
a[ [1,5,8] ]

array([31, 12, 86])

In [49]:
a  + 10 

array([107,  41, 105,  92,  42,  22,  99,  28,  96,  44])

In [50]:
a > 50

array([ True, False,  True,  True, False, False,  True, False,  True,
       False])

In [51]:
for n in a:
  if n > 50:
      print(n)

97
95
82
89
86


In [52]:
a [ a > 50 ]

array([97, 95, 82, 89, 86])

In [53]:
a [a % 2 == 0]

array([82, 32, 12, 18, 86, 34])

In [55]:
dd = np.random.randint(1,100,(5,5))

In [56]:
dd

array([[ 5, 50, 40, 36, 72],
       [42, 76, 58, 93, 60],
       [ 1,  4, 12,  4, 35],
       [97, 97, 48, 90, 27],
       [94, 35, 14, 60, 15]])

In [57]:
dd[2, dd[2] % 2 == 0]

array([ 4, 12,  4])

In [61]:
dd[2]

array([ 1,  4, 12,  4, 35])

In [62]:
a

array([97, 31, 95, 82, 32, 12, 89, 18, 86, 34])

In [65]:
a[ a < 50 ]

array([31, 32, 12, 18, 34])

In [66]:
a < 50

array([False,  True, False, False,  True,  True, False,  True, False,
        True])

### Operations on Array

In [67]:
a * 10

array([970, 310, 950, 820, 320, 120, 890, 180, 860, 340])

In [69]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
marks = np.random.randint(50,100,10)

In [3]:
marks

array([79, 96, 81, 73, 86, 91, 56, 94, 63, 82])

In [4]:
avg_marks  = marks.mean()
marks[ marks >= avg_marks]

array([96, 81, 86, 91, 94, 82])

In [6]:
marks.sum(), marks.cumsum()

(801, array([ 79, 175, 256, 329, 415, 506, 562, 656, 719, 801], dtype=int32))

In [8]:
marks.any()

True

In [15]:
marks.all()

True

In [17]:
marks.argmin()

6

In [18]:
marks.var()

152.89000000000001

In [19]:
marks.std()

12.364869590901476

In [21]:
dd = np.random.randint(1,10, (3,3))

In [22]:
dd

array([[4, 3, 3],
       [7, 5, 1],
       [1, 9, 8]])

In [23]:
dd.sum()   # Total for whole array 

41

In [24]:
dd.sum(axis=0)  # axis = 0 means column-wise sum

array([12, 17, 12])

In [26]:
dd.sum(axis=1)  # axis = 1 means row-wise sum

array([10, 13, 18])

In [27]:
marks

array([79, 96, 81, 73, 86, 91, 56, 94, 63, 82])

In [28]:
marks2 = marks[:5]

In [29]:
marks2

array([79, 96, 81, 73, 86])

In [30]:
marks2[0] = 90

In [31]:
marks

array([90, 96, 81, 73, 86, 91, 56, 94, 63, 82])

In [32]:
marks2 = marks[5:]

In [33]:
marks,marks2

(array([90, 96, 81, 73, 86, 91, 56, 94, 63, 82]), array([91, 56, 94, 63, 82]))

In [34]:
marks2[0] = 99

In [35]:
marks

array([90, 96, 81, 73, 86, 99, 56, 94, 63, 82])

### Univesal functions

In [36]:
sm = np.sqrt(marks)

In [37]:
sm

array([9.48683298, 9.79795897, 9.        , 8.54400375, 9.2736185 ,
       9.94987437, 7.48331477, 9.69535971, 7.93725393, 9.05538514])

In [38]:
sorted_marks = np.sort(marks)

In [39]:
sorted_marks

array([56, 63, 73, 81, 82, 86, 90, 94, 96, 99])

In [40]:
marks

array([90, 96, 81, 73, 86, 99, 56, 94, 63, 82])

### Reshaping array

In [41]:
a = np.random.randint(1,10,(3,4))

In [42]:
a

array([[6, 1, 5, 4],
       [7, 7, 9, 6],
       [7, 4, 1, 1]])

In [43]:
a2 = a.reshape(2,6)

In [44]:
a2

array([[6, 1, 5, 4, 7, 7],
       [9, 6, 7, 4, 1, 1]])

In [45]:
a2[0,0] = 9

In [46]:
a

array([[9, 1, 5, 4],
       [7, 7, 9, 6],
       [7, 4, 1, 1]])

In [48]:
a3 = a.reshape(4,3)

(array([7, 1, 5, 4, 7, 7, 9, 6, 7, 4, 1, 1]),
 array([7, 7, 7, 1, 7, 4, 5, 9, 1, 4, 6, 1]))

In [52]:
sd[0] = 7

In [53]:
a

array([[7, 1, 5, 4],
       [7, 7, 9, 6],
       [7, 4, 1, 1]])

In [56]:
a.ravel(), a.ravel('F')

(array([7, 1, 5, 4, 7, 7, 9, 6, 7, 4, 1, 1]),
 array([7, 7, 7, 1, 7, 4, 5, 9, 1, 4, 6, 1]))

In [58]:
b = a.flatten()

In [59]:
b[0] = 1

In [60]:
a

array([[7, 1, 5, 4],
       [7, 7, 9, 6],
       [7, 4, 1, 1]])

In [61]:
b

array([1, 1, 5, 4, 7, 7, 9, 6, 7, 4, 1, 1])

In [64]:
b.resize(15, refcheck=False)

In [65]:
b

array([1, 1, 5, 4, 7, 7, 9, 6, 7, 4, 1, 1, 0, 0, 0])

In [66]:
b.resize(10,refcheck=False)

In [67]:
b

array([1, 1, 5, 4, 7, 7, 9, 6, 7, 4])

In [68]:
a.T

array([[7, 7, 7],
       [1, 7, 4],
       [5, 9, 1],
       [4, 6, 1]])

In [69]:
a

array([[7, 1, 5, 4],
       [7, 7, 9, 6],
       [7, 4, 1, 1]])